const languages = {
    en: {
        title: 'AI Assistant',
        placeholder: 'Type your message...',
        online: 'Online',
        send: 'Send Message',
        voice: 'Voice Input',
        voiceNotSupported: 'Voice input is not supported in your browser',
        error: 'An error occurred',
        welcome: "Hello! I'm your AI assistant. How can I help you today?",
        translating: "Translating...",
        detected: "Detected language",
        translatedPrefix: "Translated: ",
        translatingAll: "Translating all messages...",
        speakMessages: "Speak messages",
        speakText: "Speak this text",
        textToSpeechActive: "Text-to-speech active",
        themes: {
            light: 'Light Theme',
            night: 'Night Theme',
            desert: 'Desert Theme',
            emerald: 'Emerald Theme',
            azure: 'Azure Theme',
            ramadan: 'Ramadan Theme',
            calligraphy: 'Calligraphy Theme'
        }
    },
    ur: {
        title: 'اے آئی اسسٹنٹ',
        placeholder: 'اپنا پیغام ٹائپ کریں...',
        online: 'آن لائن',
        send: 'پیغام بھیجیں',
        voice: 'آواز سے تحریر',
        voiceNotSupported: 'آپ کے براؤزر میں آواز سے تحریر کی سہولت دستیاب نہیں ہے',
        error: 'ایک خرابی پیش آگئی ہے',
        welcome: "السلام علیکم! میں آپ کا اے آئی اسسٹنٹ ہوں۔ میں آپ کی کیسے مدد کر سکتا ہوں؟",
        translating: "ترجمہ کر رہا ہے...",
        detected: "زبان کا پتہ چلا",
        translatedPrefix: "ترجمہ: ",
        translatingAll: "تمام پیغامات کا ترجمہ کر رہا ہے...",
        speakMessages: "پیغامات پڑھیں",
        speakText: "اس متن کو پڑھیں",
        textToSpeechActive: "ٹیکسٹ ٹو سپیچ فعال ہے",
        themes: {
            light: 'روشن تھیم',
            night: 'رات کا تھیم',
            desert: 'صحرائی تھیم',
            emerald: 'زمرد تھیم',
            azure: 'نیلا تھیم',
            ramadan: 'رمضان تھیم',
            calligraphy: 'خطاطی تھیم'
        }
    },
    ar: {
        title: 'مساعد الذكاء الاصطناعي',
        placeholder: 'اكتب رسالتك...',
        online: 'متصل',
        send: 'إرسال',
        voice: 'إدخال صوتي',
        voiceNotSupported: 'الإدخال الصوتي غير مدعوم في متصفحك',
        error: 'حدث خطأ',
        welcome: "السلام عليكم! أنا مساعدك الذكي. كيف يمكنني مساعدتك اليوم؟",
        translating: "جاري الترجمة...",
        detected: "اللغة المكتشفة",
        translatedPrefix: "مترجم: ",
        translatingAll: "جاري ترجمة جميع الرسائل...",
        speakMessages: "قراءة الرسائل",
        speakText: "قراءة هذا النص",
        textToSpeechActive: "تحويل النص إلى كلام نشط",
        themes: {
            light: 'السمة الفاتحة',
            night: 'السمة الليلية',
            desert: 'السمة الصحراوية',
            emerald: 'سمة الزمرد',
            azure: 'السمة الزرقاء',
            ramadan: 'سمة رمضان',
            calligraphy: 'سمة الخط'
        }
    },
    zh: {
        title: '人工智能助手',
        placeholder: '输入您的消息...',
        online: '在线',
        send: '发送',
        voice: '语音输入',
        voiceNotSupported: '您的浏览器不支持语音输入',
        error: '发生错误',
        welcome: "您好！我是您的AI助手。今天我能为您做些什么？",
        translating: "正在翻译...",
        detected: "检测到的语言",
        translatedPrefix: "翻译: ",
        translatingAll: "正在翻译所有消息...",
        speakMessages: "朗读消息",
        speakText: "朗读此文本",
        textToSpeechActive: "文本转语音已激活",
        themes: {
            light: '明亮主题',
            night: '夜间主题',
            desert: '沙漠主题',
            emerald: '翡翠主题',
            azure: '天蓝主题',
            ramadan: '斋月主题',
            calligraphy: '书法主题'
        }
    },
    ja: {
        title: 'AIアシスタント',
        placeholder: 'メッセージを入力...',
        online: 'オンライン',
        send: '送信',
        voice: '音声入力',
        voiceNotSupported: 'お使いのブラウザは音声入力をサポートしていません',
        error: 'エラーが発生しました',
        welcome: "こんにちは！AIアシスタントです。今日はどのようにお手伝いできますか？",
        translating: "翻訳中...",
        detected: "検出された言語",
        translatedPrefix: "翻訳: ",
        translatingAll: "すべてのメッセージを翻訳中...",
        speakMessages: "メッセージを読み上げる",
        speakText: "このテキストを読み上げる",
        textToSpeechActive: "テキスト読み上げがアクティブ",
        themes: {
            light: 'ライトテーマ',
            night: 'ナイトテーマ',
            desert: '砂漠テーマ',
            emerald: 'エメラルドテーマ',
            azure: 'アズールテーマ',
            ramadan: 'ラマダンテーマ',
            calligraphy: '書道テーマ'
        }
    },
    hi: {
        title: 'AI सहायक',
        placeholder: 'अपना संदेश लिखें...',
        online: 'ऑनलाइन',
        send: 'भेजें',
        voice: 'आवाज़ इनपुट',
        voiceNotSupported: 'आपके ब्राउज़र में आवाज़ इनपुट समर्थित नहीं है',
        error: 'एक त्रुटि हुई',
        welcome: "नमस्ते! मैं आपका AI सहायक हूँ। आज मैं आपकी कैसे मदद कर सकता हूँ?",
        translating: "अनुवाद कर रहे हैं...",
        detected: "पहचानी गई भाषा",
        translatedPrefix: "अनुवादित: ",
        translatingAll: "सभी संदेशों का अनुवाद किया जा रहा है...",
        speakMessages: "संदेश बोलें",
        speakText: "इस टेक्स्ट को बोलें",
        textToSpeechActive: "टेक्स्ट-टू-स्पीच सक्रिय",
        themes: {
            light: 'उज्जवल थीम',
            night: 'रात्रि थीम',
            desert: 'रेगिस्तान थीम',
            emerald: 'पन्ना थीम',
            azure: 'नीला थीम',
            ramadan: 'रमज़ान थीम',
            calligraphy: 'सुलेख थीम'
        }
    },
    ru: {
        title: 'ИИ-ассистент',
        placeholder: 'Введите ваше сообщение...',
        online: 'В сети',
        send: 'Отправить',
        voice: 'Голосовой ввод',
        voiceNotSupported: 'Голосовой ввод не поддерживается в вашем браузере',
        error: 'Произошла ошибка',
        welcome: "Здравствуйте! Я ваш ИИ-ассистент. Чем я могу вам помочь сегодня?",
        translating: "Перевод...",
        detected: "Обнаруженный язык",
        translatedPrefix: "Перевод: ",
        translatingAll: "Перевод всех сообщений...",
        speakMessages: "Озвучить сообщения",
        speakText: "Озвучить этот текст",
        textToSpeechActive: "Озвучивание текста активно",
        themes: {
            light: 'Светлая тема',
            night: 'Ночная тема',
            desert: 'Пустынная тема',
            emerald: 'Изумрудная тема',
            azure: 'Лазурная тема',
            ramadan: 'Тема Рамадан',
            calligraphy: 'Каллиграфическая тема'
        }
    },
    pt: {
        title: 'Assistente IA',
        placeholder: 'Digite sua mensagem...',
        online: 'Online',
        send: 'Enviar',
        voice: 'Entrada de voz',
        voiceNotSupported: 'A entrada de voz não é suportada no seu navegador',
        error: 'Ocorreu um erro',
        welcome: "Olá! Eu sou seu assistente de IA. Como posso ajudá-lo hoje?",
        translating: "Traduzindo...",
        detected: "Idioma detectado",
        translatedPrefix: "Traduzido: ",
        translatingAll: "Traduzindo todas as mensagens...",
        speakMessages: "Falar mensagens",
        speakText: "Falar este texto",
        textToSpeechActive: "Texto para fala ativo",
        themes: {
            light: 'Tema Claro',
            night: 'Tema Noturno',
            desert: 'Tema Deserto',
            emerald: 'Tema Esmeralda',
            azure: 'Tema Azure',
            ramadan: 'Tema Ramadã',
            calligraphy: 'Tema Caligrafia'
        }
    },
    tr: {
        title: 'AI Asistan',
        placeholder: 'Mesajınızı yazın...',
        online: 'Çevrimiçi',
        send: 'Gönder',
        voice: 'Sesli giriş',
        voiceNotSupported: 'Tarayıcınızda sesli giriş desteklenmiyor',
        error: 'Bir hata oluştu',
        welcome: "Merhaba! Ben AI asistanınızım. Bugün size nasıl yardımcı olabilirim?",
        translating: "Çeviriliyor...",
        detected: "Algılanan dil",
        translatedPrefix: "Çeviri: ",
        translatingAll: "Tüm mesajlar çeviriliyor...",
        speakMessages: "Mesajları seslendir",
        speakText: "Bu metni seslendir",
        textToSpeechActive: "Metin okuma etkin",
        themes: {
            light: 'Açık Tema',
            night: 'Gece Teması',
            desert: 'Çöl Teması',
            emerald: 'Zümrüt Teması',
            azure: 'Mavi Tema',
            ramadan: 'Ramazan Teması',
            calligraphy: 'Kaligrafi Teması'
        }
    },
    it: {
        title: 'Assistente AI',
        placeholder: 'Scrivi il tuo messaggio...',
        online: 'Online',
        send: 'Invia',
        voice: 'Input vocale',
        voiceNotSupported: "L'input vocale non è supportato nel tuo browser",
        error: 'Si è verificato un errore',
        welcome: "Ciao! Sono il tuo assistente AI. Come posso aiutarti oggi?",
        translating: "Traduzione in corso...",
        detected: "Lingua rilevata",
        translatedPrefix: "Tradotto: ",
        translatingAll: "Traduzione di tutti i messaggi in corso...",
        speakMessages: "Leggi messaggi",
        speakText: "Leggi questo testo",
        textToSpeechActive: "Sintesi vocale attiva",
        themes: {
            light: 'Tema Chiaro',
            night: 'Tema Notte',
            desert: 'Tema Deserto',
            emerald: 'Tema Smeraldo',
            azure: 'Tema Azzurro',
            ramadan: 'Tema Ramadan',
            calligraphy: 'Tema Calligrafia'
        }
    },
    es: {
        title: 'Asistente IA',
        placeholder: 'Escribe tu mensaje...',
        online: 'En línea',
        send: 'Enviar',
        voice: 'Entrada de Voz',
        voiceNotSupported: 'La entrada de voz no está soportada en tu navegador',
        error: 'Ocurrió un error',
        welcome: "¡Hola! Soy tu asistente de IA. ¿Cómo puedo ayudarte hoy?",
        translating: "Traduciendo...",
        detected: "Idioma detectado",
        translatedPrefix: "Traducido: ",
        translatingAll: "Traduciendo todos los mensajes...",
        speakMessages: "Leer mensajes",
        speakText: "Leer este texto",
        textToSpeechActive: "Lectura de texto activa",
        themes: {
            light: 'Tema Claro',
            night: 'Tema Nocturno',
            desert: 'Tema Desierto',
            emerald: 'Tema Esmeralda',
            azure: 'Tema Azul',
            ramadan: 'Tema Ramadán',
            calligraphy: 'Tema Caligrafía'
        }
    },
    fr: {
        title: 'Assistant IA',
        placeholder: 'Écrivez votre message...',
        online: 'En ligne',
        send: 'Envoyer',
        voice: 'Entrée Vocale',
        voiceNotSupported: "L'entrée vocale n'est pas prise en charge dans votre navigateur",
        error: "Une erreur s'est produite",
        welcome: "Bonjour! Je suis votre assistant IA. Comment puis-je vous aider aujourd'hui?",
        translating: "Traduction en cours...",
        detected: "Langue détectée",
        translatedPrefix: "Traduit: ",
        translatingAll: "Traduction de tous les messages en cours...",
        speakMessages: "Lire les messages",
        speakText: "Lire ce texte",
        textToSpeechActive: "Lecture de texte active",
        themes: {
            light: 'Thème Clair',
            night: 'Thème Nuit',
            desert: 'Thème Désert',
            emerald: 'Thème Émeraude',
            azure: 'Thème Azur',
            ramadan: 'Thème Ramadan',
            calligraphy: 'Thème Calligraphie'
        }
    },
    de: {
        title: 'KI-Assistent',
        placeholder: 'Nachricht eingeben...',
        online: 'Online',
        send: 'Senden',
        voice: 'Spracheingabe',
        voiceNotSupported: 'Spracheingabe wird in Ihrem Browser nicht unterstützt',
        error: 'Ein Fehler ist aufgetreten',
        welcome: "Hallo! Ich bin Ihr KI-Assistent. Wie kann ich Ihnen heute helfen?",
        translating: "Übersetzung läuft...",
        detected: "Erkannte Sprache",
        translatedPrefix: "Übersetzt: ",
        translatingAll: "Übersetzung aller Nachrichten läuft...",
        speakMessages: "Nachrichten vorlesen",
        speakText: "Diesen Text vorlesen",
        textToSpeechActive: "Text-zu-Sprache aktiv",
        themes: {
            light: 'Helles Design',
            night: 'Nacht-Design',
            desert: 'Wüsten-Design',
            emerald: 'Smaragd-Design',
            azure: 'Azur-Design',
            ramadan: 'Ramadan-Design',
            calligraphy: 'Kalligraphie-Design'
        }
    }
}; 